Build variants one by one

diff --git a/hooks/_conf b/hooks/_conf
--- a/hooks/_conf
+++ b/hooks/_conf
@@ -4,11 +4,49 @@ set -eu
 
 export PATH=".:$PATH"
 
-export DOCKER_TAG="${DOCKER_TAG:-latest}"
+if [ "${DOCKER_TAG:-}" == "" ]; then
+    case "$(uname -m)" in
+    x86_64)
+        export DOCKER_TAG="amd64-latest"
+        ;;
+    aarch64)
+        export DOCKER_TAG="aarch64-latest"
+        ;;
+    armv7l)
+        export DOCKER_TAG="arm32v7-latest"
+        ;;
+    armv[56]l)
+        export DOCKER_TAG="arm32v5-latest"
+        ;;
+    *)
+        echo "Cannot detect host type"
+        exit 1
+        ;;
+    esac
+fi
+
 export DOCKER_REPO="${DOCKER_REPO:-olfway/samba}"
+
+if [ "${DOCKER_REPO:=}" != "" -a "${DOCKER_REPO:0:15}" == 'index.docker.io' ]; then
+    export DOCKER_HUB="1"
+fi
 
 export DOCKER_PLATFORMS='
 {"platform":"amd64","architecture":"amd64","os":"linux"}
 {"platform":"arm32v5","architecture":"arm","os":"linux","variant":"v5"}
 {"platform":"arm32v7","architecture":"arm","os":"linux","variant":"v7"}
 {"platform":"aarch64","architecture":"arm64","os":"linux","variant":"v8"}'
+
+export DOCKER_PLATFORM_NAMES="$(echo "${DOCKER_PLATFORMS}" | jq -r ".platform" | tr '\n' ' ' | sed 's/ $//')"
+
+export DOCKER_PLATFORM_NAME="$(echo "${DOCKER_TAG}" | egrep -o "^(${DOCKER_PLATFORM_NAMES// /|})")" || true
+
+DOCKER_TAG="$(echo "$DOCKER_TAG" | sed -E "s/^${DOCKER_PLATFORM_NAME}-?//")"
+if [ "${DOCKER_TAG}" != "" ]; then
+    export DOCKER_TAG="-${DOCKER_TAG}"
+fi
+
+if [ "${GIT_SHA1:-}" == "" ]; then
+    GIT_SHA1="$(git rev-parse HEAD)"
+fi
+export DOCKER_TAG_REV="$(echo "${DOCKER_TAG}-${GIT_SHA1:0:7}")"
diff --git a/hooks/post_push b/hooks/post_push
--- a/hooks/post_push
+++ b/hooks/post_push
@@ -2,10 +2,13 @@
 
 source hooks/_conf
 
-function docker_manifest_annotate() {
+function docker_manifest_annotate_tag() {
 
-    DOCKER_PLATFORM="$1"
-    DOCKER_PLATFORM_NAME="$(echo "${DOCKER_PLATFORM}" | jq -r '.platform')"
+    local DOCKER_TAG="$1"
+    DOCKER_PLATFORM_NAME="$2"
+
+    DOCKER_PLATFORM="$(echo "${DOCKER_PLATFORMS}" | jq -cr "select(.platform == \"${DOCKER_PLATFORM_NAME}\")")"
+
     DOCKER_PLATFORM_ARCH="$(echo "${DOCKER_PLATFORM}" | jq -r '.architecture')"
 
     DOCKER_MANIFEST_ANNOTATE_ARGS="${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG} --os linux --arch ${DOCKER_PLATFORM_ARCH}"
@@ -15,21 +18,38 @@ function docker_manifest_annotate() {
         DOCKER_MANIFEST_ANNOTATE_ARGS="${DOCKER_MANIFEST_ANNOTATE_ARGS} --variant ${DOCKER_PLATFORM_VARIANT}"
     fi
 
+    echo "$(date '+%H:%M:%S') Annotating ${DOCKER_REPO}:${DOCKER_TAG} manifest with ${DOCKER_MANIFEST_ANNOTATE_ARGS}..."
     docker manifest annotate "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_MANIFEST_ANNOTATE_ARGS}
 }
 
-DOCKER_PLATFORM_REPOS=""
-for DOCKER_PLATFORM in ${DOCKER_PLATFORMS}; do
-    DOCKER_PLATFORM_NAME="$(echo "${DOCKER_PLATFORM}" | jq -r '.platform')"
-    DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS} ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}"
-done
+function docker_manifest_tag() {
 
-DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS:1}"
+    local DOCKER_TAG="${1:1}"
+    echo "$(date '+%H:%M:%S') Creating manifest ${DOCKER_REPO}:${DOCKER_TAG}..."
 
-docker manifest create "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_PLATFORM_REPOS}
+    DOCKER_PLATFORM_REPOS=""
+    for DOCKER_PLATFORM_NAME in ${DOCKER_PLATFORM_NAMES}; do
+        echo "$(date '+%H:%M:%S') Pulling ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}..."
+        docker pull "${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}" > /dev/null 2>&1 || true
+        if [ "$(docker image ls -q "${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}")" == "" ]; then
+            echo "$(date '+%H:%M:%S') Image ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG} not found"
+            exit 0
+        fi
+        DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS} ${DOCKER_REPO}:${DOCKER_PLATFORM_NAME}-${DOCKER_TAG}"
+    done
 
-for DOCKER_PLATFORM in ${DOCKER_PLATFORMS}; do
-    docker_manifest_annotate "${DOCKER_PLATFORM}"
-done
+    DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS:1}"
 
-docker manifest push "${DOCKER_REPO}:${DOCKER_TAG}"
+    echo "$(date '+%H:%M:%S') Creating manifest ${DOCKER_REPO}:${DOCKER_TAG} for ${DOCKER_PLATFORM_REPOS}..."
+    docker manifest create "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_PLATFORM_REPOS}
+
+    for DOCKER_PLATFORM_NAME in ${DOCKER_PLATFORM_NAMES}; do
+        docker_manifest_annotate_tag "${DOCKER_TAG}" "${DOCKER_PLATFORM_NAME}"
+    done
+
+    echo "$(date '+%H:%M:%S') Pushing manifest ${DOCKER_REPO}:${DOCKER_TAG}..."
+    docker manifest push "${DOCKER_REPO}:${DOCKER_TAG}"
+}
+
+docker_manifest_tag "${DOCKER_TAG_REV}"
+docker_manifest_tag "${DOCKER_TAG}"
